'''
pip install --no-cache-dir paddlepaddle==3.2.2!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
https://paddle-whl.bj.bcebos.com/stable/cpu/paddlepaddle/paddlepaddle-3.2.2-cp313-cp313-win_amd64.whl


# Скачать архивы
wget -O ./models/PP-OCRv5_mobile_det_infer.tar \
  "https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0.0/PP-OCRv5_mobile_det_infer.tar"

wget -O ./models/PP-OCRv5_mobile_rec_infer.tar \
  "https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0.0//PP-OCRv5_mobile_rec_infer.tar"

# Распаковать
tar -xf ./models/PP-OCRv5_mobile_det_infer.tar -C ./models/ppocrv5_mobile_det
tar -xf ./models/PP-OCRv5_mobile_rec_infer.tar -C ./models/ppocrv5_mobile_rec
'''

pip install "faststream[rabbit]"