syntax = "proto3";
package parsing_task_orchestrator.v1;  // namespace для .proto файла

option java_package = "io.github.maksim0840.parsing_task_orchestrator.v1";  // package для генерации .java классов из .proto файла
option java_multiple_files = true;  // для удобной генерации и обращения (каждый message/service генерируется в отдельный .java файл)

import "parsing_task_orchestrator/v1/FileInfo.proto";

// ===== Модель =====

enum TaskStatusProto {
    TASK_STATUS_UNSPECIFIED = 0;
    NOT_REGISTERED = 1;
    CREATED = 2;
    HTML_PARSING = 3;
    HTML_PREPROCESSING = 4;
    TEXT_RECOGNITION = 5;
    LLM_PROCESSING = 6;
    DONE = 7;
    FAILED = 8;
}

message HtmlParserResponseProto {
  string task_id = 1;
  bool success = 2;
  string message = 3;
  repeated FileInfoProto html_docs = 4;
  repeated FileInfoProto images = 5;
}

message HtmlPreprocessingResponseProto {
  string task_id = 1;
  bool success = 2;
  string message = 3;
  repeated FileInfoProto html_docs = 4;
}

message TextRecognitionResponseProto {
  string task_id = 1;
  bool success = 2;
  string message = 3;
  repeated FileInfoProto images = 4;
}

message LLMResponseProto {
  string task_id = 1;
  bool success = 2;
  string message = 3;
  string llm_output = 4;
}


// ===== Запросы к сервису parsing-task-orchestrator =====

message GetTaskStatusOrchestratorRequest {
    string task_id = 1;
}

message GetTaskResultOrchestratorRequest {
    string task_id = 1;
}


// ===== Ответы от сервиса parsing-task-orchestrator =====

message GetTaskStatusOrchestratorResponse {
    string task_id = 1;
    TaskStatusProto status = 2;
    string message = 3;
}

message GetTaskResultOrchestratorResponse {
    string task_id = 1;
    optional HtmlParserResponseProto html_parser_response = 2;
    optional HtmlPreprocessingResponseProto html_preprocessing_response = 3;
    optional TextRecognitionResponseProto text_recognition_response = 4;
    optional LLMResponseProto llm_response = 5;
}


// ===== Сервис (gRPC api) =====

service OrchestratorStorageService {
    rpc GetTaskStatus(GetTaskStatusOrchestratorRequest) returns (GetTaskStatusOrchestratorResponse);
    rpc GetTaskResult(GetTaskResultOrchestratorRequest) returns (GetTaskResultOrchestratorResponse);
}