syntax = "proto3";
package parsing_task_orchestrator.v1;  // namespace для .proto файла

option java_package = "io.github.maksim0840.parsing_task_orchestrator.v1";  // package для генерации .java классов из .proto файла
option java_multiple_files = true;  // для удобной генерации и обращения (каждый message/service генерируется в отдельный .java файл)

import "parsing_task_orchestrator/v1/FileInfo.proto";

// ===== Модель =====

message HtmlParserRequestProto {
  string task_id = 1;
  string url = 2;
  string html_out_dir = 3;
  string images_out_dir = 4;
  optional bool download_images = 5;
  map<string, string> headers = 6;
  map<string, string> cookies = 7;
  map<string, string> proxy = 8;
  optional string page_complexity = 9;
  optional int32 additional_page_load_timeout_s = 10;
}

message HtmlPreprocessingRequestProto {
  string task_id = 1;
  repeated FileInfoProto html_docs = 2;
  optional bool noscript_processing = 3;
  optional bool link_processing = 4;
  optional bool style_processing = 5;
  optional bool meta_processing = 6;
  optional bool script_processing = 7;
  optional bool canvas_processing = 8;
  optional bool svg_processing = 9;
  optional bool area_processing = 10;
  optional bool img_processing = 11;
  optional bool video_processing = 12;
  optional bool audio_processing = 13;
  optional bool iframe_processing= 14;
  optional bool portal_processing = 15;
  optional bool embed_processing = 16;
  optional bool object_processing = 17;
  optional bool source_processing = 18;
}

message TextRecognitionRequestProto {
  string task_id = 1;
  repeated FileInfoProto images = 2;
}

message LLMRequestProto {
    string task_id = 1;
    string model_name = 2;
    string system_message = 3;
    string user_message = 4;
    optional double temperature = 5;
    optional int32 max_output_tokens = 6;
    repeated FileInfoProto html_docs = 7;
    repeated FileInfoProto images = 8;
}


// ===== Запросы к сервису parsing-task-orchestrator =====

message StartParsingOrchestratorRequest {
    string task_id = 1;
    string user_id = 2;
    optional HtmlParserRequestProto html_parser_request = 3;
    optional HtmlPreprocessingRequestProto html_preprocessing_request = 4;
    optional TextRecognitionRequestProto text_recognition_request = 5;
    optional LLMRequestProto llm_request = 6;
}


// ===== Ответы от сервиса parsing-task-orchestrator =====

message StartParsingOrchestratorResponse {
    string task_id = 1;
}


// ===== Сервис (gRPC api) =====

service OrchestratorStartService {
  rpc StartParsing(StartParsingOrchestratorRequest) returns (StartParsingOrchestratorResponse);
}