syntax = "proto3";
package parsing_task_orchestrator.v1;  // namespace для .proto файла

option java_package = "io.github.maksim0840.parsing_task_orchestrator.v1";  // package для генерации .java классов из .proto файла
option java_multiple_files = true;  // для удобной генерации и обращения (каждый message/service генерируется в отдельный .java файл)

// ===== Модель =====

message HtmlParserRequestProto {
  string url = 1;
  string html_out_dir = 2;
  string images_out_dir = 3;
  optional bool download_images = 4;
  optional map<string, string> headers = 5;
  optional map<string, string> cookies = 6;
  optional map<string, string> proxy = 7;
  optional string page_complexity = 8;
  optional int32 additional_page_load_timeout_s = 9;
}

message HtmlPreprocessingRequestProto {
  repeated string html_paths = 1;
  optional bool noscript_processing = 2;
  optional bool link_processing = 3;
  optional bool style_processing = 4;
  optional bool meta_processing = 5;
  optional bool script_processing = 6;
  optional bool canvas_processing = 7;
  optional bool svg_processing = 8;
  optional bool area_processing = 9;
  optional bool img_processing = 10;
  optional bool video_processing = 11;
  optional bool audio_processing = 12;
  optional bool iframe_processing= 13;
  optional bool portal_processing = 14;
  optional bool embed_processing = 15;
  optional bool object_processing = 16;
  optional bool source_processing = 17;
}

message TextRecognitionRequestProto {
  repeated string image_paths = 1;
}

message HtmlParserResponseProto {
  string html_path = 1;
  repeated string image_paths = 2;
}

message HtmlPreprocessingResponseProto {
  repeated string html_paths = 1;
}

message TextRecognitionResponseProto {
  map<string, string> text_by_image = 1;
}


// ===== Запросы к сервису parsing-task-orchestrator =====

message ParsingRequest {
    optional HtmlParserRequestProto html_parser_request = 1;
    optional HtmlPreprocessingRequestProto html_preprocessing_request = 2;
    optional TextRecognitionRequestProto text_recognition_request = 3;
}


// ===== Ответы от сервиса parsing-task-orchestrator =====

message ParsingResponse {
    optional HtmlParserResponseProto html_parser_response = 1;
    optional HtmlPreprocessingResponseProto html_preprocessing_response = 2;
    optional TextRecognitionResponseProto text_recognition_response = 3;
}


// ===== Сервис (gRPC api) =====

service ParsingTaskOrchestratorService {
  rpc Start(ParsingRequest) returns (ParsingResponse);
}