services:

  orchestrator:
    build:
      context: ..   # главная директория ai-parsing-web
      dockerfile: parsing-task-orchestrator-microservice/Dockerfile
    image: orchestrator:dev
    env_file:
      - llm.env
      - s3_settings.env
    networks:
      - rabbitmq-net
      - redis-orchestrator-net
      - grpc-orchestrator-api-net
      - garage-net
    depends_on:
      - redis_orchestrator
      - rabbitmq
      
  redis_orchestrator:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - redis-orchestrator-net
    volumes:
      - redis_orchestrator_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - "5673:5672"     # AMQP
      - "15673:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq-net

 
volumes:
  redis_orchestrator_data:
  rabbitmq_data:
  
  
networks:
  redis-orchestrator-net:
  rabbitmq-net:
    external: true
    name: rabbitmq-net
  grpc-orchestrator-api-net:
    external: true
    name: grpc-orchestrator-api-net
  garage-net:
    external: true
    name: garage-net
