server:
  port: 8080

grpc:
  client:
    extraction_results:
      address: dns:///results:9090
      negotiationType: plaintext
    users_info:
      address: dns:///users:9091
      negotiationType: plaintext
    parsing_orchestrator_start:
      address: dns:///orchestrator:9092
      negotiationType: plaintext

  server:
    port: 9093 # parsing_orchestrator_finish

s3:
  access_key: ${S3_ACCESS_KEY)
  secret_key: ${S3_SECRET_KEY}
  endpoint_url: ${S3_ENDPOINT_URL:http://garage:3900}
  path_style_access: ${S3_PATH_STYLE_ACCESS:true}
  region_name: ${S3_REGION_NAME:garage}
  bucket_name: ${S3_TTL_7D_BUCKET_NAME}
