server:
  port: 8080

grpc:
  client:
    extraction_results:
      address: dns:///results:9090
      negotiationType: plaintext
    users_info:
      address: dns:///users:9091
      negotiationType: plaintext
    parsing_orchestrator_start:
      address: dns:///orchestrator:9092
      negotiationType: plaintext

  server:
    port: 9093 # parsing_orchestrator_finish

