services:
  garage:
    image: dxflrs/garage:v2.2.0
    container_name: garage
    restart: unless-stopped
    ports:
      - "3900:3900"  # S3 API
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - ./meta:/var/lib/garage/meta
      - ./data:/var/lib/garage/data
    networks:
      - garage-net

networks:
  garage-net:
    driver: bridge
    external: true
    name: garage-net
