services:

  api:
    build:
      context: ..   # главная директория ai-parsing-web
      dockerfile: api-gateway-microservice/Dockerfile
    image: api:dev
    ports:
      - "8080:8080"
    networks:
      - garage-net
      
networks:
  garage-net:
    external: true
    name: garage-net
