services:

  api:
    build:
      context: ..   # главная директория ai-parsing-web
      dockerfile: api-gateway-microservice/Dockerfile
    image: api:dev
    env_file:
      - connection.env
      - security.env
    ports:
      - "8080:8080"
    networks:
      - garage-net
      - grpc-orchestrator-api-net
      - grpc-results-api-net
      - grpc-users-api-net
      
networks:
  garage-net:
    external: true
    name: garage-net
  grpc-orchestrator-api-net:
    external: true
    name: grpc-orchestrator-api-net
  grpc-results-api-net:
    external: true
    name: grpc-results-api-net
  grpc-users-api-net:
    external: true
    name: grpc-users-api-net
