spring:
  application:
    name: parsing-orchestrator

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /

server:
  port: 8080


rabbitmq:
  html_parser_queue:
    request_name: html_parser_queue_request
    response_name: html_parser_queue_response

  text_recognition_queue:
    request_name: text_recognition_queue_request
    response_name: text_recognition_queue_response