spring:
  application:
    name: parsing-orchestrator
  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    password: admin123
    virtual-host: /
server:
  port: 8080

data:
  mongodb:
    uri: mongodb://localhost:27017/tasks

grpc:
  client:
    parsing_orchestrator_result:
      address: static://localhost:9093
      negotiationType: plaintext

  server:
    port: 9092 # parsing_orchestrator_entry

rabbitmq:
  html_parser_queue:
    request_name: html_parser_queue_request
    response_name: html_parser_queue_response

  html_preprocessing_queue:
    request_name: html_preprocessing_queue_request
    response_name: html_preprocessing_queue_response

  text_recognition_queue:
    request_name: text_recognition_queue_request
    response_name: text_recognition_queue_response