spring:
  application:
    name: parsing-orchestrator

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin123
    virtual-host: /

  data:
    mongodb:
      uri: mongodb://mongodb_orchestrator:27017/tasks

server:
  port: 8080

grpc:
  client:
    parsing_orchestrator_finish:
      address: static://api:9093
      negotiationType: plaintext

  server:
    port: 9092 # parsing_orchestrator_start

rabbitmq:
  html_parser_queue:
    request_name: html_parser_queue_request
    response_name: html_parser_queue_response

  html_preprocessing_queue:
    request_name: html_preprocessing_queue_request
    response_name: html_preprocessing_queue_response

  text_recognition_queue:
    request_name: text_recognition_queue_request
    response_name: text_recognition_queue_response